# production： 产品环境 (默认为此环境)　；　development　为开发环境　；　　test:　测试环境
test:
   productId: ^[1-9]\d{3,4}$#123#配置异常,必须为4~5位纯数字! 配置参数格式:9998
   gamePort: ^[1-9]\d{3,4}$#123#配置异常,必须为4~5位纯数字! 配置参数格式:9998
   resPort: ^[1-9]\d{3,4}$#123#配置异常,必须为4~5位纯数字! 配置参数格式:9998
   webPort: ^[1-9]\d{3,4}$#123#配置异常,必须为4~5位纯数字! 配置参数格式:9998
   activityURL: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格！配置参数格式:http://127.0.0.1:20001/
   shoppingCenterURL: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格！配置参数格式：http://192.168.7.6:9999/shoppingCenter
   serverURL: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格！配置参数格式:172.17.42.1
   zookeeperIp: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格！配置参数格式:192.168.8.25
   langPath: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格！配置参数格式:lang/lang_zh.txt
   pyjRecordPath: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格！配置参数格式:./fileData/pyjrecord/
   appid: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格！配置参数格式:wx34eaf9458518c3be
   userIdPrefix: ^[1-9]\d{9}$#123#配置异常,必须为8位纯数字!配置参数格式:4200000000
   userIdLength: ^8$#123#配置异常,必须为8！配置参数格式:8
   
   
   cacheConfig: 
      port: ^[1-9]\d{3,4}$#123#配置异常,必须为4~5位纯数字! 配置参数格式:9998
      url: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格,配置参数格式:127.0.0.1
      database: ^\d$#123#配置异常,必须为纯数字!配置参数格式:6
      database2: ^\d$#123#配置异常,必须为纯数字!配置参数格式:7
      #passwd: ^[^\s]{1,}$#123#配置异常,不能为空或空格或包含空格！配置参数格式:XXsd@DFs
      
      
         #发牌控制
   cardControlConfig:
      probability:
          gt6: ^\d{1,}$#123#配置异常,必须为纯数字!配置参数格式:20
          gt5: ^\d{1,}$#123#配置异常,必须为纯数字!配置参数格式:10
          gt4: ^\d{1,}$#123#配置异常,必须为纯数字!配置参数格式:0
          lt1.5: ^\d{1,}$#123#配置异常,必须为纯数字!配置参数格式:30
      n: ^\d{1,}$#123#配置异常,必须为纯数字!配置参数格式:3
      types:
          dz: ^\d$#123#配置异常,必须为纯数字!配置参数格式:1
          kz: ^\d{1,}|\d{1,}.\d{1,}$#123#配置异常,必须为数字或带小数的数字!配置参数格式:1.5
          sg: ^\d$#123#配置异常,必须为纯数字!配置参数格式:2
          sz: ^\d{1,}|\d{1,}.\d{1,}$#123#配置异常,必须为数字或带小数的数字!配置参数格式:1.5